### ISSUE TITLE
Feature Request: -red and +green color highlighting for diff/patch pastes

### ISSUE THREAD

**Issue by drjaska** [SergioBenitez/rktpb#1]
Examples with GitHub's text formatting:

(setup)

```sh
echo "a" > a.txt
echo "b" > b.txt
diff a.txt b.txt
```

diff output from `diff`:

```diff
1c1
< a
---
> b
```

git diff:

```diff
diff --git a/bin/youtube-dl b/bin/youtube-dl
index 0096a5c..83f7447 100755
--- a/bin/youtube-dl
+++ b/bin/youtube-dl
@@ -2,4 +2,4 @@
 
 set -eu
 
-yt-dlp "$@"
+yt-dlp --sponsorblock-remove default "$@"
```

**Comment by SergioBenitez** [comment]
This now renders nicely:

<img width="803" alt="Screenshot 2024-04-17 at 3 42 55 PM" src="https://github.com/SergioBenitez/rktpb/assets/1480321/a16cb31d-594b-4dfb-a08d-278258e8b57b">
