### ISSUE TITLE
Firefox reports the website as harmful

### ISSUE THREAD

**Issue by terry90** [SergioBenitez/rktpb#3]
![image](https://github.com/user-attachments/assets/9e417e55-ff5d-4e3f-8902-96e29a3ff32b)

**Comment by terry90** [comment]
Chrome also

![image](https://github.com/user-attachments/assets/0f753661-239d-4f49-b283-057f65833f83)

**Comment by SergioBenitez** [comment]
Firefox is just using the Google list, and Google is complaining about some markdown files someone pasted with links to malware. I've removed those files and asked Google for a review, so at some point this should go away.

**Comment by SergioBenitez** [comment]
Looks like Google has removed it from their list!
